name: Variables

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # variable to target/demo-0.0.1.jar
    JAR_FILE: target/demo-0.0.1.jar

jobs:
  build-jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: demo-jar
          path: ${{ env.JAR_FILE }}

  build-docker-image:
    needs: build-jar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: demo-jar
          path: target

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
